name: CD - Simulação de Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Simular deploy
      run: echo "Deploy realizado com sucesso!"
