name: CI - Verificação de Código

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Verificar estrutura do projeto
      run: echo "CI executado com sucesso!"
